### ISSUE TITLE
大佬国服出了还玩吗？

### ISSUE THREAD

**Issue by xuchuankun1027** [hojin-go/maplestory-m-script#3]
大佬国服出了还玩吗？

**Comment by mikeooye** [comment]
韩服没有汉化后就没在玩了，最近一直在玩国服，在安卓蓝蜗牛。

**Comment by xuchuankun1027** [comment]
我在安卓蘑菇仔
我本来准备学学AutoXjs把你这脚本改改呢
大佬你国服有脚本吗？

**Comment by mikeooye** [comment]
有，不过不是用的autojs写的，是手机上一个软件实现的，可以把角色每天的任务脚本走一遍。

**Comment by xuchuankun1027** [comment]
啥软件啊？类似于按键精灵那种？需要root吗？
求大佬指点

**Comment by mikeooye** [comment]
叫“自动执行精灵”，不需要root，你研究研究看看，我主要用找图片点击来实现

**Comment by guanzaizai** [comment]
大佬，我只搜到自动精灵，是自动执行精灵吗，能否给个链接

**Comment by mikeooye** [comment]
> 大佬，我只搜到自动精灵，是自动执行精灵吗，能否给个链接

下载链接为：http://lesson.jsgogogo.com/dianji-latest.apk

**Comment by guanzaizai** [comment]
> > 大佬，我只搜到自动精灵，是自动执行精灵吗，能否给个链接
> 
> 下载链接为：http://lesson.jsgogogo.com/dianji-latest.apk

thk
